name: Sync to Hugging Face hub
on:
  push:
    branches: [develop]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HGF: ${{ secrets.HGF }}
        run: git remote add space https://taranjitkaurme:$HGF@huggingface.co/spaces/taranjitkaurme/test
      - name: Push to hub
        env:
          HGF: ${{ secrets.HGF }}
        run: git push --force https://taranjitkaurme:$HGF@huggingface.co/spaces/taranjitkaurme/test develop
